import { Injectable } from '@angular/core';
import { generateClient } from 'aws-amplify/data';
import { type Schema } from '../../../amplify/data/resource';
import { BehaviorSubject, Observable } from 'rxjs';
import { NoteI } from '../interfaces/notes';
import { LabelI } from '../interfaces/labels';

@Injectable({
    providedIn: 'root'
})
export class AmplifyDataService {
    private client = generateClient<Schema>();

    private notesSubject = new BehaviorSubject<NoteI[]>([]);
    public notes$ = this.notesSubject.asObservable();

    private labelsSubject = new BehaviorSubject<LabelI[]>([]);
    public labels$ = this.labelsSubject.asObservable();

    constructor() {
        this.initSubscriptions();
    }

    private initSubscriptions() {
        this.client.models.Note.observeQuery().subscribe({
            next: (data) => {
                // Map Amplify models to NoteI (ensure types match)
                // IDs are strings in Amplify, so we assume NoteI is updated to string ID.
                this.notesSubject.next(data.items as unknown as NoteI[]);
            },
            error: (err) => console.error('Error observing notes', err)
        });

        this.client.models.Label.observeQuery().subscribe({
            next: (data) => {
                this.labelsSubject.next(data.items as unknown as LabelI[]);
            },
            error: (err) => console.error('Error observing labels', err)
        });
    }

    async addNote(note: NoteI) {
        // ID is auto-generated by Amplify if not present
        const { id, ...rest } = note;
        // Remove local ID if present (if number, we drop it. if string, we might keep it if needed, but safer to let Amplify generate)
        // Actually, if we are editing, we keep ID. If adding, we drop it?
        // NoteI usually has no ID when adding.
        return await this.client.models.Note.create(rest as any);
    }

    async updateNote(note: NoteI) {
        if (!note.id) return;
        const { ...rest } = note;
        return await this.client.models.Note.update(rest as any);
    }

    async deleteNote(id: string) {
        return await this.client.models.Note.delete({ id });
    }

    async addLabel(label: LabelI) {
        return await this.client.models.Label.create(label as any);
    }

    async updateLabel(label: LabelI) {
        if (!label.id) return;
        return await this.client.models.Label.update(label as any);
    }

    async deleteLabel(id: string) {
        return await this.client.models.Label.delete({ id });
    }

    // TODO: Implement complex update logic or "updateAllLabels" equivalent if needed.
}
