import { Injectable } from '@angular/core';
import { generateClient } from 'aws-amplify/data';
import { type Schema } from '../../../amplify/data/resource';
import { BehaviorSubject, Observable } from 'rxjs';
import { NoteI } from '../interfaces/notes';
import { LabelI } from '../interfaces/labels';
import { db } from '../db/db';

@Injectable({
    providedIn: 'root'
})
export class AmplifyDataService {
    private client = generateClient<Schema>();

    private notesSubject = new BehaviorSubject<NoteI[]>([]);
    public notes$ = this.notesSubject.asObservable();

    private labelsSubject = new BehaviorSubject<LabelI[]>([]);
    public labels$ = this.labelsSubject.asObservable();

    private isAmplifyConnected = true;

    constructor() {
        // Check if Amplify outputs contain placeholder values and force local storage mode
        this.checkAmplifyConfiguration();
        this.initSubscriptions();
    }

    private checkAmplifyConfiguration() {
        // Check if any placeholder values exist in the config
        const outputs = (window as any).amplifyConfig || {};
        const hasPlaceholders = 
            outputs.auth?.user_pool_id?.includes('PLACEHOLDER') ||
            outputs.auth?.user_pool_client_id?.includes('PLACEHOLDER') ||
            outputs.data?.url?.includes('PLACEHOLDER') ||
            outputs.data?.api_key?.includes('PLACEHOLDER') ||
            outputs.data?.url?.includes('dummy'); // Our mock values
        
        if (hasPlaceholders) {
            console.log('Amplify configuration has placeholder values, using local storage mode');
            this.isAmplifyConnected = false;
            this.loadFromLocalStorage();
            this.loadLabelsFromLocalStorage();
        }
    }

    private initSubscriptions() {
        // Only attempt Amplify subscriptions if we believe connection is viable
        if (this.isAmplifyConnected) {
            this.client.models.Note.observeQuery().subscribe({
                next: (data: any) => {
                    // Map Amplify models to NoteI (ensure types match)
                    // IDs are strings in Amplify, so we assume NoteI is updated to string ID.
                    this.notesSubject.next(data.items as unknown as NoteI[]);
                },
                error: (err: any) => {
                    console.error('Error observing notes, falling back to local storage', err);
                    this.isAmplifyConnected = false;
                    this.loadFromLocalStorage();
                }
            });

            this.client.models.Label.observeQuery().subscribe({
                next: (data: any) => {
                    this.labelsSubject.next(data.items as unknown as LabelI[]);
                },
                error: (err: any) => {
                    console.error('Error observing labels, falling back to local storage', err);
                    this.isAmplifyConnected = false;
                    this.loadLabelsFromLocalStorage();
                }
            });
        }
    }

    private async loadFromLocalStorage() {
        try {
            const notes = await db.notes.toArray();
            this.notesSubject.next(notes as unknown as NoteI[]);
        } catch (error) {
            console.error('Error loading from local storage', error);
        }
    }

    private async loadLabelsFromLocalStorage() {
        try {
            const labels = await db.labels.toArray();
            this.labelsSubject.next(labels as unknown as LabelI[]);
        } catch (error) {
            console.error('Error loading labels from local storage', error);
        }
    }

async addNote(note: NoteI) {
        if (this.isAmplifyConnected) {
            try {
                // ID is auto-generated by Amplify if not present
                const { id, ...rest } = note;
                // Remove local ID if present (if number, we drop it. if string, we might keep it if needed, but safer to let Amplify generate)
                // Actually, if we are editing, we keep ID. If adding, we drop it?
                // NoteI usually has no ID when adding.
                return await this.client.models.Note.create(rest as any);
            } catch (error) {
                console.error('Amplify connection failed, falling back to local storage', error);
                this.isAmplifyConnected = false;
                return await this.addNoteToLocalStorage(note);
            }
        } else {
            return await this.addNoteToLocalStorage(note);
        }
    }

    private async addNoteToLocalStorage(note: NoteI) {
        try {
            const id = await db.notes.add(note as any);
            return { data: { id: id.toString() } };
        } catch (error) {
            console.error('Error adding note to local storage', error);
            throw error;
        }
    }

    async updateNote(note: NoteI) {
        if (!note.id) return { data: null };
        
        if (this.isAmplifyConnected) {
            try {
                const { ...rest } = note;
                return await this.client.models.Note.update(rest as any);
            } catch (error) {
                console.error('Amplify connection failed, falling back to local storage', error);
                this.isAmplifyConnected = false;
                return await this.updateNoteInLocalStorage(note);
            }
        } else {
            return await this.updateNoteInLocalStorage(note);
        }
    }

    private async updateNoteInLocalStorage(note: NoteI) {
        try {
            const numericId = parseInt(note.id as string);
            await db.notes.update(numericId, note as any);
            return { data: note };
        } catch (error) {
            console.error('Error updating note in local storage', error);
            throw error;
        }
    }

async deleteNote(id: string) {
        if (this.isAmplifyConnected) {
            try {
                return await this.client.models.Note.delete({ id });
            } catch (error) {
                console.error('Amplify connection failed, falling back to local storage', error);
                this.isAmplifyConnected = false;
                return await this.deleteNoteFromLocalStorage(id);
            }
        } else {
            return await this.deleteNoteFromLocalStorage(id);
        }
    }

    private async deleteNoteFromLocalStorage(id: string) {
        try {
            const numericId = parseInt(id);
            await db.notes.delete(numericId);
            return { data: { id } };
        } catch (error) {
            console.error('Error deleting note from local storage', error);
            throw error;
        }
    }

async addLabel(label: LabelI) {
        if (this.isAmplifyConnected) {
            try {
                return await this.client.models.Label.create(label as any);
            } catch (error) {
                console.error('Amplify connection failed, falling back to local storage', error);
                this.isAmplifyConnected = false;
                return await this.addLabelToLocalStorage(label);
            }
        } else {
            return await this.addLabelToLocalStorage(label);
        }
    }

    private async addLabelToLocalStorage(label: LabelI) {
        try {
            const id = await db.labels.add(label as any);
            return { data: { id: id.toString() } };
        } catch (error) {
            console.error('Error adding label to local storage', error);
            throw error;
        }
    }

    async updateLabel(label: LabelI) {
        if (!label.id) return;
        
        if (this.isAmplifyConnected) {
            try {
                return await this.client.models.Label.update(label as any);
            } catch (error) {
                console.error('Amplify connection failed, falling back to local storage', error);
                this.isAmplifyConnected = false;
                return await this.updateLabelInLocalStorage(label);
            }
        } else {
            return await this.updateLabelInLocalStorage(label);
        }
    }

    private async updateLabelInLocalStorage(label: LabelI) {
        try {
            const numericId = parseInt(label.id as string);
            await db.labels.update(numericId, label as any);
            return { data: label };
        } catch (error) {
            console.error('Error updating label in local storage', error);
            throw error;
        }
    }

    async deleteLabel(id: string) {
        if (this.isAmplifyConnected) {
            try {
                return await this.client.models.Label.delete({ id });
            } catch (error) {
                console.error('Amplify connection failed, falling back to local storage', error);
                this.isAmplifyConnected = false;
                return await this.deleteLabelFromLocalStorage(id);
            }
        } else {
            return await this.deleteLabelFromLocalStorage(id);
        }
    }

    private async deleteLabelFromLocalStorage(id: string) {
        try {
            const numericId = parseInt(id);
            await db.labels.delete(numericId);
            return { data: { id } };
        } catch (error) {
            console.error('Error deleting label from local storage', error);
            throw error;
        }
    }

    // TODO: Implement complex update logic or "updateAllLabels" equivalent if needed.
}
